apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx    # helm install hello-world-1 ./chart-path => hello-world-1-nginx
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app: hello-world
    template:
      metadata:
        labels:
          app: hello-world
      spec:
        containers:
          - name: hello-world
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
              - name: http
                containerPort: 80
                protocol: TCP