apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  {{- if .Values.orgLabel }}
  labels:
    org:  {{ .Values.orgLabel }}
  {{- end }}
spec:
  selector:
    app: hello-world
  ports:
    - name: http
      port: 80
